"""Module to collect action data

Provide a simple interface into action properties

Roleplay action commands are defined as individual YAML files in "actions" subfolder
"""

import logging
from dataclasses import dataclass, field
from pathlib import Path
from random import choice

import yaml

# Pairing tags in image filenames, e.g. hug_wlw_1234.gif. mlw and wlm are different pairings.
PAIRINGS = ("mlw", "wlm", "wlw", "mlm")
# Without a requested pairing, wlw and mlm images are left out
DEFAULT_PAIRINGS = {None, "mlw", "wlm"}
IMAGE_SUFFIXES = {".gif", ".png", ".jpg", ".jpeg", ".webp"}
# The pools the member site's gallery shows: what the bot picks from without a pairing, and the two it leaves out.
POOLS = ("default", "wlw", "mlm")


def pairing_of(path: Path) -> str | None:
    """The pairing tag in an image's filename, or None if it's untagged."""
    return next((part for part in path.stem.lower().split("_") if part in PAIRINGS), None)


def pool_of(path: Path) -> str:
    """Which of POOLS an image is in, decided the same way pick_image does."""
    pairing = pairing_of(path)
    return pairing if pairing and pairing not in DEFAULT_PAIRINGS else "default"


def is_ai_made(name: str) -> bool:
    """Whether an image's file name marks it as AI-made: it has ``eros`` in it, in any case (``hug_eros_1234.gif``)."""
    return "eros" in name.lower()


def image_files(folder: Path) -> list[Path]:
    """The images in an action's folder (subfolders included), by filename. A missing folder has none."""
    files = (f for f in folder.rglob("*") if f.is_file() and f.suffix.lower() in IMAGE_SUFFIXES)
    return sorted(files, key=lambda f: (f.name, str(f)))


def pick_image(folder: Path, pairing: str | None = None) -> tuple[Path | None, bool]:
    """A random image from an action's folder (subfolders included).

    With ``pairing``, only images tagged with it are used; if there are none, the
    default pool is used instead.

    Returns:
        The image (None if there's nothing to pick from), and whether the requested
        pairing had no images.
    """
    files = image_files(folder)
    if pairing:
        tagged = [f for f in files if pairing_of(f) == pairing]
        if tagged:
            return choice(tagged), False
    pool = [f for f in files if pairing_of(f) in DEFAULT_PAIRINGS]
    return (choice(pool) if pool else None), pairing is not None


@dataclass
class Consent:
    """Represents the consent properties for an action.

    Attributes:
        active (str): The message displayed when asking for active consent.
            Ex: "{target_member}, {invoker_member} wants to ___ you."
        passive (str): The message displayed when asking for passive consent.
            Ex: "{invoker_member}, {target_member} wants you to ___ them."
        owner_active (str): The message displayed when asking for consent from an owner(s).
            Ex: "{owner}, {invoker_member} wants to ___ {target_member}."
        owner_passive (str): The message displayed when asking for consent from an owner(s).
            Ex: "{owner}, {invoker_member} wants {target_member} to ___ them."
        required (bool): Indicates the action requires consent (default is True).
    """

    active: str
    passive: str
    owner_active: str
    owner_passive: str
    required: bool = True


@dataclass
class Action:
    """Represents an action in roleplay.

    Attributes:
        name (str): The name of the action.
        help (str): The docstring added to each action command method. Displayed in 'help' messages generated by the bot.
        description (str): The Embed description, describing the roleplay action in present tense. Use {invoker_member} and {target_member} tags.
        consent (Consent): Messages used to ask for consent, and whether consent is required.
        aliases (Optional[List[str]]): Aliases for the command name.
        credits (Optional[List[str]]): Optional credits text included in the Embed footer to acknowledge members who came up with the idea.
        spoiler (Optional[bool]): Use for lewd images. This will spoiler the image in a message instead of displaying it in an Embed.

    The action's images are the files in its folder of the cog's images data folder, see pick_image().
    """

    name: str
    description: str
    help: str
    consent: Consent
    aliases: list[str] = field(default_factory=list)
    credits: list[str] | None = None
    spoiler: bool = False

    def __post_init__(self):
        # YAML gives plain strings and dicts; normalize them to the declared types
        if self.description is None:
            self.description = "{invoker_member} is " + f"{self.name}ing" + " {target_member}."
        if self.help is None:
            self.help = f"{self.name}s a member."
        if isinstance(self.aliases, str):
            self.aliases = [self.aliases]
        if isinstance(self.consent, dict):
            self.consent = Consent(**self.consent)


class ActionManager:
    DATA_PATH = Path(__file__).parent / "actions"

    def __init__(self):
        self.logger = logging.getLogger("red.kirin_cogs.roleplay.actions")

        self.actions: list[Action] = []

        self.load_all()

    def __str__(self):
        actions = [str(action) for action in self.actions]
        actions = "\n\t".join(actions)
        return f"ActionManager: {actions}"

    def load(self, action_name: str, file_path: Path) -> Action | None:
        try:
            with open(file_path, encoding="utf-8") as file:
                data = yaml.safe_load(file)
            return Action(name=action_name, **data)
        except (yaml.YAMLError, TypeError):
            self.logger.exception(f"Error trying to load {file_path}!")
            return None

    def load_all(self):
        yaml_files = (file for pattern in ("*.yaml", "*.yml") for file in self.DATA_PATH.glob(pattern))

        loaded = [action for file_path in yaml_files if (action := self.load(file_path.stem, file_path))]
        # Red's cog update copies files over the installed cog without deleting removed ones, so a retired
        # action's file (pet.yml) can still be there after it became another action's alias (pat's)
        aliases = {alias.lower() for action in loaded for alias in action.aliases}
        for action in loaded:
            if action.name.lower() in aliases:
                self.logger.warning(f'Skipping action "{action.name}": it is another action\'s alias now.')
            else:
                self.actions.append(action)

    def _find(self, action_name: str) -> Action | None:
        key = action_name.lower()
        for action in self.actions:
            if key == action.name.lower() or key in (alias.lower() for alias in action.aliases):
                return action
        return None

    def get(self, action_name: str) -> Action | None:
        """Find an action by its name or one of its aliases, ignoring case."""
        action = self._find(action_name)
        if action is None:
            self.logger.warning(f'Unable to find action "{action_name}"!')
        return action

    def canonical(self, action_name: str) -> str:
        """The action's name for a stored name that may have become an alias (``pet`` is now ``pat``).

        Names that aren't an action any more are kept as they are."""
        action = self._find(action_name)
        return action.name if action else action_name

    def list(self) -> list[str]:
        return sorted(action.name for action in self.actions)
