"""Module to collect action data

Provide a simple interface into action properties

Roleplay action commands are defined as individual YAML files in "actions" subfolder
"""

import logging
from dataclasses import dataclass, field
from pathlib import Path

import yaml


@dataclass
class Consent:
    """Represents the consent properties for an action.

    Attributes:
        active (str): The message displayed when asking for active consent.
            Ex: "{target_member}, {invoker_member} wants to ___ you."
        passive (str): The message displayed when asking for passive consent.
            Ex: "{invoker_member}, {target_member} wants you to ___ them."
        owner_active (str): The message displayed when asking for consent from an owner(s).
            Ex: "{owner}, {invoker_member} wants to ___ {target_member}."
        owner_passive (str): The message displayed when asking for consent from an owner(s).
            Ex: "{owner}, {invoker_member} wants {target_member} to ___ them."
        required (bool): Indicates the action requires consent (default is True).
    """

    active: str
    passive: str
    owner_active: str
    owner_passive: str
    required: bool = True


@dataclass
class Action:
    """Represents an action in roleplay.

    Attributes:
        name (str): The name of the action.
        help (str): The docstring added to each action command method. Displayed in 'help' messages generated by the bot.
        description (str): The Embed description, describing the roleplay action in present tense. Use {invoker_member} and {target_member} tags.
        consent (Consent): Messages used to ask for consent, and whether consent is required.
        aliases (Optional[List[str]]): Aliases for the command name.
        credits (Optional[List[str]]): Optional credits text included in the Embed footer to acknowledge members who came up with the idea.
        spoiler (Optional[bool]): Use for lewd images. This will spoiler the image in a message instead of displaying it in an Embed.
        images (Optional[list]): URL for a gif(s) that represents the action.
    """

    name: str
    description: str
    help: str
    consent: Consent
    aliases: list[str] = field(default_factory=list)
    credits: list[str] | None = None
    spoiler: bool = False
    images: list[str] = field(default_factory=list)
    # the image URLs from the action's file, kept after images switches to local files
    image_urls: list[str] = field(init=False, default_factory=list)

    def __post_init__(self):
        # YAML gives plain strings and dicts; normalize them to the declared types
        if self.description is None:
            self.description = "{invoker_member} is " + f"{self.name}ing" + " {target_member}."
        if self.help is None:
            self.help = f"{self.name}s a member."
        if isinstance(self.aliases, str):
            self.aliases = [self.aliases]
        if isinstance(self.images, str):
            self.images = [self.images]
        self.image_urls = list(self.images)
        if isinstance(self.consent, dict):
            self.consent = Consent(**self.consent)


class ActionManager:
    DATA_PATH = Path(__file__).parent / "actions"

    def __init__(self):
        self.logger = logging.getLogger(f"{__name__}.{self.__class__.__name__}")

        self.actions: list[Action] = []

        self.load_all()

    def __str__(self):
        actions = [str(action) for action in self.actions]
        actions = "\n\t".join(actions)
        return f"ActionManager: {actions}"

    def load(self, action_name: str, file_path: Path) -> Action | None:
        try:
            with open(file_path, encoding="utf-8") as file:
                data = yaml.safe_load(file)
            return Action(name=action_name, **data)
        except (yaml.YAMLError, TypeError):
            self.logger.exception(f"Error trying to load {file_path}!")
            return None

    def load_all(self):
        yaml_files = (file for pattern in ("*.yaml", "*.yml") for file in self.DATA_PATH.glob(pattern))

        for file_path in yaml_files:
            action = self.load(file_path.stem, file_path)
            if action:
                self.actions.append(action)

    def update_images(self, action: Action, images_path: Path):
        # Look for locally cached images and replace the list of URLs with a list
        # of these filepaths
        action_images_path = images_path / action.name
        if not action_images_path.is_dir():
            self.logger.debug(f"{action_images_path} is not a valid directory.")
            return

        image_files = [file.as_posix() for file in action_images_path.iterdir() if file.is_file()]
        if not image_files:
            self.logger.debug(f"No cached images for {action.name} in {action_images_path}.")
            return

        action.images = image_files
        self.logger.debug(f"{action.name} is now using local image cache")

    def update(self, images_path: Path):
        for action in self.actions:
            self.update_images(action, images_path)

    def get(self, action_name: str) -> Action | None:
        """Find an action by its name or one of its aliases, ignoring case."""
        key = action_name.lower()
        for action in self.actions:
            if key == action.name.lower() or key in (alias.lower() for alias in action.aliases):
                return action

        self.logger.warning(f'Unable to find action "{action_name}"!')
        return None

    def list(self) -> list[str]:
        return sorted(action.name for action in self.actions)
