# ruff: noqa: RUF001  # the questions keep the typographic apostrophes they were written with
"""The built-in questions: the list Unicornia's copy of Jintaku's conversationgames used, deduplicated, plus
spicier ones added since.

Approved member suggestions are stored per server in Config and added to these.
"""

TRUTHS = [
    "What was the last thing you searched for on your phone?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "After you've dropped a piece of food, what's the longest time you've left it on the ground and then ate it?",
    "Play “fuck, marry, kill” with three people in the chat.",
    "Where is the craziest place you’ve ever had sex?",
    "Have you ever peed in the pool?",
    "What’s the kinkiest thing you’ve ever done in bed?",
    "What is your favorite kink?",
    "What’s the biggest lie you’ve told someone to get them into bed with you?",
    "Who was your first kiss?",
    "What’s a popular fetish that you would never want to try?",
    "Have you ever practiced kissing in a mirror?",
    "What’s your favorite body part on your body?",
    "What is your worst habit?",
    "Have you ever walked into a wall?",
    "Do you ever talk to yourself in the mirror?",
    "What’s the least amount of time you’ve gone between having sex with two different people?",
    "What would be in your web history that you’d be embarrassed if someone saw?",
    "What’s the most amount of people you’ve kissed in one night?",
    "Have you ever been tempted to cheat on your significant other?",
    "What’s your favorite position?",
    "Who do you like the least here and why?",
    "What is your go-to song for the shower?",
    "Who is the sexiest person in this server?",
    "How would you rate your looks on a scale of 1 to 10?",
    "What don't you like about me?",
    "What color underwear are you wearing right now?",
    "What’s the smallest amount of time you’ve known someone before sleeping with them?",
    "Have you ever been caught having sex?",
    "Do you ever apply makeup without using the mirror?",
    "Who is the oddest person you’ve ever had a sexual fantasy about?",
    "Do you prefer sex when you’re in love or when it’s a hot hookup?",
    "Tell me your weirdest habit.",
    "Do you like parties?",
    "What position is popular that you think is overrated?",
    "Who is the most annoying person among your friends?",
    "How many (sex) partners have you had?",
    "Suppose you were a billionaire, how would you spend your time?",
    "Who in the chat do you think has slept with the most people?",
    "If you wanted to start your own business, what it would be?",
    "Have you ever had the crush on someone much younger or older than you? What’s the biggest age difference?",
    "When was the last time you touched yourself?",
    "Have you ever had sex and immediately gotten up and left?",
    "Who was your worst kiss ever?",
    "Who is the worst kisser you have ever kissed and why?",
    "What is your favorite villain character?",
    "Have you ever called someone 'Daddy' or been called 'Daddy' while having sex?",
    "Do you like when I act or talk dirty to you?",
    "Do you like having sex in the morning or evening?",
    "Have you ever seen a dead body?",
    "What do you wish you had learned about sex way earlier than you did?",
    "Have you ever laughed out when doing it and what is the reason?",
    "Whom would you love to date amongst the people in the chat?",
    "When was the first time you fell in love and with whom?",
    "What has been the most embarrassing moment you've experienced so far?",
    "Tell us about your secret fantasy.",
    "What turns you on the most?",
    "Have you ever cheated on your partner?",
    "What is the most sensual piece of clothing you own?",
    "When was your first time?",
    "Have you ever gone skinny dipping?",
    "When was the first time you kissed someone? Who was it?",
    "Have you got a secret talent?",
    "Pick one person from chat you'd like to exchange your partners with!",
    "Has anyone ever walked in on you in the bathroom?",
    "What was your best sexual experience?",
    "What is the longest you’ve ever given head?",
    "Would you ever do a threesome?",
    "How do you feel about sex in groups?",
    "Would you ever watch your partner have sex with someone else?",
    "How many partners have you had at one time?",
    "Describe how your orgasms feel?",
    "Where is your favourite place to be kissed?",
    "What’s the last song that made you cry?",
    "What is the longest time you’ve gone without sex?",
    "Do you prefer rough or slow sex?",
    "Do you prefer to be on top or bottom?",
    "What is your favourite position?",
    "What is your least favourite position?",
    "Have you ever had sex outside?",
    "Where is the strangest place you’ve ever had sex?",
    "Have you ever paid for sex?",
    "Who was your first partner?",
    "Have you ever made a lewd video of yourself?",
    "Who is your favourite porn star?",
    "What is your favourite type of porn?",
    "Have you ever thought about being a stripper?",
    "Do you prefer the lights on or off (during sex)?",
    "Does size matter?",
    "Do you prefer to have music in the background, or for it to be be quiet?",
    "Do you prefer for your partner to be silent, or do you like moans?",
    "Do you like a lot of foreplay?",
    "What is your favourite type of foreplay?",
    "Have you done role-playing?",
    "What is your role-playing fantasy?",
    "What is your “sweet spot”?",
    "What is your strangest sexual fantasy?",
    "Would you ever have sex for money?",
    "How flexible are you?",
    "How many orgasms have you had in one sexual encounter?",
    "Spit or swallow?",
    "Who is your crush?",
    "Who is the most annoying person you know?",
    "Have you ever lied to your parents about what you were doing after school?",
    "How many partners have you had?",
    "What is your biggest pet peeve?",
    "Have you ever told one of your best friend’s secrets, even if you said you wouldn’t?",
    "Have you ever had a crush on someone that your best friend has dated?",
    "If you were a billionaire, what would you spend your time doing?",
    "What is the longest time that you think you could go without your cell phone?",
    "What is the most expensive thing you own?",
    "What is your favourite kind of clothing?",
    "What is your favourite song that is out right now?",
    "Have you ever walked in on your parents doing it?",
    "What are some things you think about when sitting on the toilet?",
    "What is your guilty pleasure?",
    "Do you sing in the shower?",
    "What was your most embarrassing moment in public?",
    "What was the last thing you texted?",
    "Do you think you'll marry your current partner?",
    "What is the most illegal thing you have ever done?",
    "Would you trade in your pet for a million dollars?",
    "Would you rather lose your sex organs forever or gain 200 pounds?",
    "If you could only hear one song for the rest of your life, what would it be?",
    "Who in the chat would be the worst person to date? Why?",
    "If someone offered you $1 million dollars to break up with your partner, would you do it?",
    "If you were reborn, what decade would you want to be born in?",
    "Have you ever thought about cheating on your partner?",
    "Have you ever been caught checking someone out?",
    "Describe the strangest dream you've ever had. Did you like it?",
    "Do you pee in the shower?",
    "The world ends next week and you can do anything you want. What would you do?",
    "Would you wear your shirt inside out for a whole day if someone paid you $100?",
    "Tell us about a time you embarrassed yourself in front of a crush.",
    "If you had to make out with any Disney character, who would it be?",
    "Have you ever wanted to try LARP (Live Action Role-Play)?",
    "What app on your phone do you waste the most time on?",
    "Do you dance when you’re by yourself?",
    "Do you still take bubble baths?",
    "How many selfies do you take a day?",
    "What is something you’ve done to try to be ‘cooler’?",
    "Have you ever eaten something off the floor?",
    "Have you ever butt-dialed someone?",
    "Have you ever got caught doing something you shouldn’t?",
    "What part of your body do you love and which part do you hate?",
    "What is something that no one else knows about you?",
    "Do you write in a diary?",
    "Who would you hate to see naked?",
    "If you could only text one person for the rest of your life, but you could never talk to that person face to face, who would that be?",
    "What's one thing you would never eat on a first date?",
    "What have you seen that you wish you could unsee?",
    "If you could be reincarnated into anyone's body, who would you want to become?",
    "Are you interested in furries?",
    "What's one food that you will never order at a restaurant?",
    "If you could only use one swear word for the rest of your life, which one would you choose?",
    "If you could date anyone in the world, who would you date?",
    "Describe your perfect date.",
    "You have to delete every app on your except for five. Name the five you would keep.",
    "Have you ever gotten mad at a friend for posting an unflattering picture of you?",
    "Who do you think is the cutest person in this server?",
    "What is the most attractive feature on a person?",
    "What the biggest deal breaker for you?",
    "How far would you go on a first date?",
    "Describe what makes someone husband or wife material.",
    "What's one thing you do that you don't want anyone to know about?",
    "Do you frequently stalk anyone on social media? Who?",
    "Who do you want to make out with the most?",
    "Of the people in the chat, who would you go out with?",
    "Describe the most attractive thing about each person in the chat.",
    "Who here do you think is the best flirt?",
    "Who here has the best smile?",
    "Who here has the cutest nose?",
    "Who's the funniest in this chat?",
    "What's one thing you would never do in front of someone you had a crush on?",
    "How often do you check yourself out in the mirror when you're on a date?",
    "Who here do you think would be the best kisser?",
    "If you could have one physical feature of someone in this chat, what would that be?",
    "How far would you go with someone you just met and will never see again?",
    "Rate me on a scale of 1 to 10, with 10 being the hottest.",
    "If I was a food, what would I be, and how would you eat me?",
    "If you had one week to live and you had to marry someone in this server, who would it be?",
    "If you only had 24 hours to live and you could do anything with anyone in this server, who would it be and what would you do with that person?",
    "What's your biggest turn-on?",
    "Would you go out with me if I was the last person on earth?",
    "What's the most flirtatious thing you've ever done?",
    "If you could go on a romantic date with anyone in this chat, who would you pick?",
    "If you had to delete one app from your phone, what would it be?",
    "What is your greatest fear in a relationship?",
    "Say one positive and one negative thing about each person in the chat.",
    "Have you ever tried drugs?",
    "What's the craziest thing you've done while under the influence?",
    "If you were trapped for three days on an island, who are three people in this server you would bring with you and why?",
    "Would you go to a nude beach?",
    "Who's the most annoying person in this chat?",
    "If you had to marry someone in this server, who would it be?",
    "How long was your longest relationship?",
    "Do you want to have kids? How many?",
    "Would you ever get into a long distance relationship?",
    "Have you ever thought about being locked up in chastity?",
    "How tall do you want to be?",
    "Who do you think is the hottest celebrity?",
    "What actor or actress do you want to fuck most?",
    "What's the weirdest thing you've used to masturbate?",
    "How many times have you faked an orgasm?",
    "Have you ever been to a nudist beach? Would you consider going?",
    "Who do you most want to sleep with, out of everyone here?",
    "If you had only three things to bring to a deserted island, what would they be and why?",
    "What's your favorite body part on your partner?",
    "How many people have you kissed?",
    "When and where was your first kiss? Who was it with?",
    "What's your ultimate sexual fantasy?",
    "Do you sleep in the nude?",
    "Have you ever been in a friends with benefits situation?",
    "If you had to go skinny dipping with someone, who in this chat would you choose?",
    "What's one thing you've always wanted to explore sexually but haven't?",
    "Have you ever used a sex toy in public (discreetly or otherwise)?",
    "What's your stance on ethical non-monogamy or polyamory?",
    "Describe a time you felt truly empowered by your sexuality.",
    "What's a boundary you've had to set in a sexual or kink dynamic?",
    "What's your favorite type of aftercare?",
    "Have you ever been in a power exchange dynamic? Describe it.",
    "What's your favorite way to express affection or intimacy?",
    "What's a fetish or kink you find intriguing but don't necessarily participate in?",
    "What's a fantasy you have that you haven't shared with anyone before?",
    "What's a common misconception about a kink you enjoy that you'd like to correct?",
    "What does 'aftercare' ideally look like for you?",
    "What's the weirdest place you've ever thought about having sex?",
    "What's an instant 'ick' for you when you're getting to know someone romantically/sexually?",
    "If your sex life was a movie title, what would it be?",
    "What's a surprisingly intimate non-sexual act for you?",
    # Spicier additions, 27 September 2026
    "What's the most embarrassing thing that's happened to you in the middle of a scene?",
    "Which kink did you discover most recently, and how did you find it?",
    "What's your safeword, or what would it be?",
    "What's the best thing someone could whisper in your ear right now?",
    "Are you more of a brat or a good pet? Give the chat evidence.",
    "What's a toy you own that you've never actually used?",
    "What's the most you've ever spent on one toy or piece of gear?",
    "What's the naughtiest thing you've done on a video call?",
    "Have you ever been caught with a toy? By whom?",
    "What's the filthiest thing you've ever said in bed?",
    "Describe the dirtiest message still sitting in your phone. Don't send it, just describe it.",
    "Who in this server would you trust to tie you up?",
    "Who in this server would you most like to have on a leash?",
    "What's a kink you used to be against but now love?",
    "What does your ideal scene look like, from start to finish?",
    "What's the longest you've ever been edged or denied?",
    "Which part of your body gets the most compliments in bed?",
    "What's the riskiest place you've ever gotten off?",
    "What's the kinkiest thing you've ever bought online?",
    "Do you have a crush on someone in this server? Are they in chat right now?",
    "What do you like being called in bed?",
    "What's one word that instantly turns you on?",
    "What sound do you make when you're really enjoying yourself?",
    "Collar, cuffs or blindfold: pick one and explain why.",
    "What's the longest session you've ever had?",
    "Have you ever had a sex dream about someone in this server?",
    "Have you ever sexted someone you met here?",
    "What's the most daring outfit you've ever worn out in public?",
    "What's something you'd normally only admit to a partner? Admit it now.",
    "What's the first thing you notice about someone you find hot?",
    "What's the hottest compliment you've ever gotten?",
    "What's something about sex you pretended to know about but didn't?",
    "Have you ever hooked up with someone you met online?",
    "Who's the most dominant person you've ever been with, and how did it feel?",
    "What's the most submissive thing you've ever done?",
    "If you owned someone here for a day, what would their first rule be?",
    "What's the best punishment you've ever been given?",
    "What gets you into subspace or headspace fastest?",
    "Have you ever been told you're too loud in bed?",
    "Have you ever gone commando somewhere fancy?",
    "What scenario would you roleplay with someone in this chat tonight?",
    "What's the most creative thing you've ever used as a restraint?",
    "What's the most people you've flirted with at the same time?",
    "Rate your own kinkiness from 1 to 10, then let the chat rate you.",
    "When did you last take a lewd picture, and who was it for?",
    "If you had to swap kink lists with someone here, whose would you take?",
    "What do you most want to hear during aftercare?",
    "What's the most control you've ever handed over to someone?",
    "What's your biggest turn-off in the bedroom?",
    "Which of your kinks would surprise your friends the most?",
    "Marks or no marks: how do you feel about bruises and hickeys?",
    "What do you love being teased about?",
    "Would you rather give orders or follow them? Why?",
    "What would you want to try with more than one partner?",
    "What's the hottest scene you've ever watched or read?",
    "Have you ever been with someone far more experienced than you? What did they teach you?",
    "What have you always wanted to be asked in bed but never have been?",
    "Who here gives off the strongest dom energy?",
    "Who here gives off the strongest sub energy?",
    "What's the kinkiest thing you've done that nobody in this server knows about?",
]

DARES = [
    "Set your crush's profile picture as your profile picture.",
    "Send a screenshot of your search history of the last day.",
    "Send the most recent photo of your gallery.",
    "Send your ugliest selfie.",
    "Flash a lewd picture of yourself in nsfw chat.",
    "Message something bold to someone hot you’ve been wanting to get to know.",
    "Kiss (&kiss) someone in the chat that you’re attracted to.",
    "Call me and sing a song for me.",
    "Send me a pic of you wearing the least clothes on you.",
    "Be my one day boyfriend or girlfriend.",
    "Write your and my name in your status for 1 day.",
    "Propose to me in the most sensual way possible.",
    "Add the bimbo role to yourself for 1 day.",
    "Send me the last message you received from your crush.",
    "Send a feet picture of yours in <#716958329892634634>",
    "Send a a hand picture of yours in <#816005759992463430>",
    "Open your gallery, close your eyes, scroll randomly and select one picture and send it to me.",
    "Send a text message to your crush while your eyes are closed.",
    "Put my picture as your mobile wallpaper for three days.",
    "Send next five text messages to your friends using your elbow only.",
    "Send five photo from your gallery.",
    "Use the '&fuck' or '&suck' command on someone who you are attracted to here.",
    "Post a picture of your favorite piece of gear or a symbol representing your identity in the chat.",
    "Send a voice note saying something dominant or submissive (whichever is outside your comfort zone) in a private DM to someone in the chat.",
    "Write a short, spicy haiku and post it in the chat.",
    "DM someone in the chat and tell them one specific thing you find attractive about them.",
    "Write a one-sentence story involving a rope and a willing participant.",
    "Change your nickname to something related to a kink or identity for an hour.",
    "Send a picture of your favorite piece of lingerie or underwear.",
    "Write a short compliment for the person who gave you this dare.",
    "Describe your 'type' using only three adjectives.",
    "Send a picture of your favorite collar or piece of BDSM jewelry.",
    "Write a short affirmation about self-love and acceptance and post it in the chat.",
    "Use &hug or &pat at the person who gave you this dare.",
    "Describe your ideal date night, including any kink elements.",
    "Write a short, non-explicit scene involving a dominant and a submissive character.",
    "Write a very short (3-5 sentence) erotic story snippet using the last three people who spoke in chat as characters (with their permission, or use archetypes).",
    "For the next 10 messages you send in chat, end them with '...and that's how I like it.'",
    # Spicier additions, 27 September 2026
    "Use &spank on someone who's been a brat today.",
    "Use &bite on the last person who made you blush.",
    "Use &ask spank on the person you trust to do it right.",
    "Use &tuckin on whoever you think needs aftercare right now.",
    "Use &uppies on the smallest person in chat.",
    "Run &compat on your crush and post the result, whatever it says.",
    "Run &compat on the two people in chat you'd most like to see together.",
    "Post your &rpstats and explain your top action.",
    "Name one member you'd let &peg you, or explain why nobody deserves the honour.",
    "Let the person who dared you pick your nickname for the next hour (within the rules).",
    "Describe what you're wearing right now in as much detail as the chat asks for.",
    "Write a filthy one-line pickup line for the person above you.",
    "Tell the chat your safeword and the story behind it.",
    "Describe your last orgasm using only emojis.",
    "Describe your type's body using only emojis.",
    "Rate the last three people who talked in chat on how much fun they'd be to tie up.",
    "Confess your most recent dirty thought, word for word.",
    "Beg the person who dared you for mercy as dramatically as you can.",
    "Post a picture of your favourite toy, piece of gear or outfit in an NSFW channel.",
    "Pick someone in chat and describe, in three sentences, the scene you'd plan for them.",
    'Write a five-point "how to handle me" manual.',
    'Call the person who dared you "Sir", "Ma\'am" or "Master" for your next ten messages.',
    'Add "please" to every message you send for the next 15 minutes.',
    "Tell the chat which part of you you'd want worshipped, and how.",
    "Describe your wildest sexual experience in exactly ten words.",
    "Describe the kinkiest thing in your search history.",
    'Write a one-sentence dirty story that starts with "The collar clicked shut..."',
    "Let someone in chat give you one order, and follow it (within the rules).",
    "Ask the person you find hottest here what their favourite position is.",
    'Post a selfie with your best "come here" look.',
    "Answer the next question you're asked using only moans and emojis.",
    "Ask someone in chat if you may flirt with them. If they say yes, send them your best line.",
    'Change your status to "Owned by" the person who dared you for an hour, if they agree.',
    "Describe what you'd do with a blindfold and five minutes.",
    "Tell the chat about the worst possible moment you've ever gotten turned on.",
    "Paste the last flirty message you sent, with the names taken out.",
    "Send a voice note moaning the name of the person who dared you, if they agree.",
    "Give the person above you a dom or sub title, and use it every time you talk to them for the next hour.",
]

# Would you rather: (first option, second option)
WYR = [
    ("always be 10 minutes late", "always be 20 minutes early"),
    ("lose all of your money and valuables", "all of the pictures you have ever taken"),
    ("be able to see 10 minutes into your own future", "10 minutes into the future of anyone but yourself"),
    ("be famous when you are alive and forgotten when you die", "unknown when you are alive but famous after you die"),
    (
        "go to jail for 4 years for something you didn’t do",
        "get away with something horrible you did but always live in fear of being caught",
    ),
    (
        "accidentally be responsible for the death of a child",
        "accidentally be responsible for the deaths of three adults",
    ),
    ("your shirts be always two sizes too big", "one size too small"),
    ("live in the wilderness far from civilization", "live on the streets of a city as a homeless person"),
    (
        "the general public think you are a horrible person but your family be very proud of you",
        "your family think you are a horrible person but the general public be very proud of you",
    ),
    ("live your entire life in a virtual reality where all your wishes are granted", "in the real world"),
    ("be alone for the rest of your life", "always be surrounded by annoying people"),
    ("never use social media sites / apps again", "never watch another movie or TV show"),
    ("have an easy job working for someone else", "work for yourself but work incredibly hard"),
    ("be the first person to explore a planet", "be the inventor of a drug that cures a deadly disease"),
    ("have a horrible short term memory", "a horrible long term memory"),
    ("be completely invisible for one day", "be able to fly for one day"),
    ("be locked in a room that is constantly dark for a week", "a room that is constantly bright for a week"),
    ("be poor but help people", "become incredibly rich by hurting people"),
    ("live without the internet", "live without AC and heating"),
    (
        "have a horrible job, but be able to retire comfortably in 10 years",
        "have your dream job, but have to work until the day you die",
    ),
    ("find your true love", "a suitcase with five million dollars inside"),
    ("be able to teleport anywhere", "be able to read minds"),
    ("die in 20 years with no regrets", "die in 50 years with many regrets"),
    ("be feared by all", "loved by all"),
    ("be transported permanently 500 years into the future", "500 years into the past"),
    ("never be able to use a touchscreen", "never be able to use a keyboard and mouse"),
    ("be able to control fire", "water"),
    ("have everything you eat be too salty", "not salty enough no matter how much salt you add"),
    ("have hands that kept growing as you got older", "feet that kept growing as you got older"),
    ("be unable to use search engines", "unable to use social media"),
    ("give up bathing for a month", "give up the internet for a month"),
    ("donate your body to science", "donate your organs to people who need them"),
    ("go back to age 5 with everything you know now", "know now everything your future self will learn"),
    ("relive the same day for 365 days", "lose a year of your life"),
    ("have a golden voice", "a silver tongue"),
    ("be able to control animals (but not humans) with your mind", "control electronics with your mind"),
    ("sell all of your possessions", "sell one of your organs"),
    ("lose all of your memories from birth to now", "lose your ability to make new long term memories"),
    ("be infamous in history books", "be forgotten after your death"),
    ("never have to work again", "never have to sleep again (you won’t feel tired or suffer negative health effects)"),
    ("be beautiful / handsome but stupid", "intelligent but ugly"),
    ("get one free round trip international plane ticket every year", "be able to fly domestic anytime for free"),
    ("be balding but fit", "overweight with a full head of hair"),
    ("be able to be free from junk mail", "free from email spam for the rest of your life"),
    (
        "be fluent in all languages and never be able to travel",
        "be able to travel anywhere for a year but never be able to learn a word of a different language",
    ),
    ("have an unlimited international first class ticket", "never have to pay for food at restaurants"),
    ("see what was behind every closed door", "be able to guess the combination of every safe on the first try"),
    (
        "live in virtual reality where you are all powerful",
        "live in the real world and be able to go anywhere but not be able to interact with anyone or anything",
    ),
    ("never be able to eat meat", "never be able to eat vegetables"),
    ("give up watching TV / movies for a year", "give up playing games for a year"),
    ("always be able to see 5 minutes into the future", "always be able to see 100 years into the future"),
    ("super sensitive taste", "super sensitive hearing"),
    ("be a practicing doctor", "a medical researcher"),
    ("be married to a 10 with a bad personality", "a 6 with an amazing personality"),
    ("never be able to drink sodas like coke again", "only be able to drink sodas and nothing else"),
    ("be a reverse centaur", "a reverse mermaid/merman"),
    ("have constantly dry eyes", "a constant runny nose"),
    ("be a famous director", "a famous actor"),
    ("not be able to open any closed doors (locked or unlocked)", "not be able to close any open doors"),
    ("give up all drinks except for water", "give up eating anything that was cooked in an oven"),
    ("have to read aloud every word you read", "sing everything you say out loud"),
    (
        "have whatever you are thinking appear above your head for everyone to see",
        "have absolutely everything you do live streamed for anyone to see",
    ),
    (
        "be put in a maximum security federal prison with the hardest of the hardened criminals for one year",
        "be put in a relatively relaxed prison where wall street types are held for ten years",
    ),
    (
        "have a clown only you can see that follows you everywhere and just stands silently in a corner watching you without doing or saying anything",
        "have a real life stalker who dresses like the Easter bunny that everyone can see",
    ),
    ("kill one innocent person", "five people who committed minor crimes"),
    ("have a completely automated home", "a self-driving car"),
    ("work very hard at a rewarding job", "hardly have to work at a job that isn’t rewarding"),
    ("be held in high regard by your parents", "your friends"),
    ("be an amazing painter", "a brilliant mathematician"),
    ("be reincarnated as a fly", "just cease to exist after you die"),
    (
        "be able to go to any theme park in the world for free for the rest of your life",
        "eat for free at any drive through restaurant for the rest of your life",
    ),
    (
        "be only able to watch the few movies with a rotten tomatoes score of 95-100%",
        "only be able to watch the majority of movies with a rotten tomatoes score of 94% and lower",
    ),
    ("never lose your phone again", "never lose your keys again"),
    ("have one real get out of jail free card", "a key that opens any door"),
    (
        "have a criminal justice system that actually works and is fair",
        "an administrative government that is free of corruption",
    ),
    ("have real political power but be relatively poor", "be ridiculously rich and have no political power"),
    ("have the power to gently nudge anyone’s decisions", "have complete puppet master control of five people"),
    (
        "have everyone laugh at your jokes but not find anyone else’s jokes funny",
        "have no one laugh at your jokes but you still find other people’s jokes funny",
    ),
    (
        "be the absolute best at something that no one takes seriously",
        "be well above average but not anywhere near the best at something well respected",
    ),
    ("lose the ability to read", "lose the ability to speak"),
    ("live under a sky with no stars at night", "live under a sky with no clouds during the day"),
    ("humans go to the moon again", "go to mars"),
    ("never get angry", "never be envious"),
    ("have free Wi-Fi wherever you go", "be able to drink unlimited free coffee at any coffee shop"),
    ("be compelled to high five everyone you meet", "be compelled to give wedgies to anyone in a green shirt"),
    (
        "live in a house with see-through walls in a city",
        "in the same see-though house but in the middle of a forest far from civilization",
    ),
    (
        "take amazing selfies but all of your other pictures are horrible",
        "take breathtaking photographs of anything but yourself",
    ),
    ("use a push lawn mower with a bar that is far too high", "far too low"),
    (
        "be able to dodge anything no matter how fast it’s moving",
        "be able ask any three questions and have them answered accurately",
    ),
    # Spicier additions, 27 September 2026
    ("be tied up and teased for an hour", "do the tying and the teasing"),
    ("only ever be praised in bed", "only ever be degraded in bed"),
    ("have a partner who talks dirty nonstop", "have one who stays completely silent"),
    ("be edged for a whole week", "have one amazing orgasm and then none for a month"),
    ("wear a collar in public for a day", "wear a vibrator someone else controls for a day"),
    ("give up kissing forever", "give up oral forever"),
    ("have your browser history read out in chat", "have your last ten sent messages read out"),
    ("be the brat who gets punished", "be the one handing out the punishment"),
    ("only have sex with the lights on", "only have sex in the dark"),
    ("be blindfolded", "be gagged"),
    ("have a partner with endless stamina", "have one who knows exactly what you like"),
    ("only ever have quickies", "only ever have marathon sessions"),
    ("be caught mid-act by your neighbour", "be caught mid-act by your boss"),
    ("tell your partner your wildest fantasy", "act it out without saying a word first"),
    ("be spanked", "be tickled until you beg"),
    ("wear a plug to a fancy dinner", "wear no underwear to a wedding"),
    ("be someone's pet for a week", "have a pet of your own for a week"),
    ("hear your partner moan", "hear your partner beg"),
    ("have morning sex every day", "have late-night sex every day"),
    ("hook up in a fancy hotel room", "hook up in the back seat of a car"),
    ("be locked in chastity for a month", "not be allowed to touch your partner for a month"),
    ("have rope marks for a week", "have hickeys for a week"),
    ("only use toys", "only use hands and mouths"),
    ("be praised in front of everyone", "be degraded in private"),
    ("be the centre of attention at a play party", "watch everything from the corner"),
    ("have a safeword you have to sing", "have a safeword you have to shout"),
    ("only be able to sext in voice notes", "only be able to sext in emojis"),
    ("be woken up with kisses", "be woken up with a spanking"),
    ("be owned by someone in this chat", "own someone in this chat"),
    ("have your kinks read out at a family dinner", "have your limits read out at a job interview"),
]

# Never have I ever: each starts with ...
NHIE = [
    "...watched the Ghostbusters remake.",
    "...wanted to be one of the Kardashians.",
    "...dressed as the opposite sex.",
    "...watched Spongebob Squarepants.",
    "...cried during a Pixar movie.",
    "...had a crush, or man crush, on Ron Swanson.",
    "...'cleaned up' by piling everything into a closet.",
    "...sung karaoke.",
    "...watched the 'Gangnam Style' music video.",
    "...had a crush on someone from 'Full House'.",
    "...watched an episode of 'Gilmore Girls'.",
    "...pretended to know a stranger.",
    "...worn sleepwear and pretended it was clothing.",
    "...said 'excuse me' when there was no one around.",
    "...scared myself in a mirror.",
    "...missed a high five.",
    "...heard someone else doing it.",
    "...sang in the shower.",
    "...blamed farts on an animal.",
    "...secretly wished I were a wizard at Hogwarts.",
    "...slept in regular clothing.",
    "...had a nightmare about zombies chasing me.",
    "...pretended to laugh at a joke I didn't get.",
    "...been scared of clowns.",
    "...thought a cartoon character was hot.",
    "...faked being sick so I could play video games.",
    "...liked Star Wars more than Star Trek.",
    "...tried out to be an extra in a movie.",
    "...scored over 100 while bowling.",
    "...used an Instant Pot.",
    "...played Candy Crush.",
    "...won a game of Scrabble.",
    "...made a duck face when taking a selfie.",
    "...looked out the car's passenger seat window and imagined it was a scene from a music video.",
    "...actually laughed out loud when typing 'lol'.",
    "...reread an email immediately after sending it.",
    "...daydreamed about being on a talk show and what I'd talk about.",
    "...Googled my own name to see what comes up.",
    "...pretended I was running from zombies while on a run.",
    "...sat in the shower.",
    "...tried something I saw on Pinterest.",
    "...ugly cried for no reason.",
    "...creeped on someone I just met on social media.",
    "...thought about how a loved one could identify me if my face was horribly disfigured in an accident.",
    "...answered someone 'left' or 'right' without thinking, because I have a 50/50 chance of being right.",
    "...been out of the country.",
    "...regifted a gift card.",
    "...traveled out of state by myself.",
    "...flown in a helicopter.",
    "...been on stage in front of a crowd.",
    "...lied in a job interview.",
    "...stalked a crush.",
    "...agreed with something Donald Trump said.",
    "...thought about what type of dog I would be.",
    "...watched children's cartoons I'm too old for.",
    "...lost sunglasses that I was already wearing.",
    "...locked my keys in my car.",
    "...not tipped at a restaurant.",
    "...given money to a homeless person.",
    "...tried to look at the sun.",
    "...bungee-jumped.",
    "...had surgery.",
    "...jumped out of a plane.",
    "...made a wish at a fountain.",
    "...accidentally eaten a bug.",
    "...cut someone in line.",
    "...stayed up all night.",
    "...read a single Harry Potter book.",
    "...been inside of a library.",
    "...lied about my age.",
    "...shot a gun.",
    "...had a cavity.",
    "...been mini golfing.",
    "...seen an elephant in real life.",
    "...been to Disney World.",
    "...bought clothing online.",
    "...had someone draw a caricature of me.",
    "...owned an Xbox.",
    "...spent hours watching funny videos on Youtube.",
    "...seen Titanic.",
    "...met a celebrity.",
    "...thought a movie was better than the book.",
    "...voted.",
    "...owned a watch.",
    "...ridden a skateboard.",
    "...learned how to play a musical instrument.",
    "...seen snow.",
    "...finished a Sudoku puzzle.",
    "...Googled something so I'd know how to spell it.",
    "...cheated on a test.",
    "...cried watching Homeward Bound.",
    "...licked a frozen pole.",
    "...had gum in my hair.",
    "...taken a horrible picture on picture day.",
    "...been a bully.",
    "...wanted to be a superhero.",
    "...been scared of the dark.",
    "...had trouble sleeping after watching a scary movie.",
    "...been to a sleepover.",
    "...had a birthday party.",
    "...cried at school.",
    "...sang on a stage.",
    "...performed in a talent show.",
    "...killed ants with a magnifying glass.",
    "...dropped Mentos into Coke or Pepsi.",
    "...eaten something on a dare.",
    "...used the excuse 'my dog ate my homework'.",
    "...sucked my thumb.",
    "...believed my toys had feelings.",
    "...watched Blue's Clues.",
    "...been terrified of a theme park ride.",
    "...been to a haunted house.",
    "...dressed up as a zombie for Halloween.",
    "...been sent to the principle's office.",
    "...done an Easter Egg Hunt.",
    "...built a fort with blankets.",
    "...fallen off a bike.",
    "...played video games all day.",
    "...stolen money from a sibling's piggy bank.",
    "...wished I had bunk beds.",
    "...played Pokemon.",
    "...been on a family road trip.",
    "...named a stuffed animal.",
    "...used training wheels.",
    "...eaten only candy for dinner.",
    "...stayed in character all day.",
    "...lied about being related to someone on tv.",
    "...written notes on the desk to use during a test.",
    "...tried to sign a permission slip for my parents.",
    "...stolen a friend's story and pretend it happened to me.",
    "...thrown something out of the school bus window.",
    "...lied about staying after school and went somewhere else.",
    "...hopped seats on the school bus.",
    "...accidentally sharted.",
    "...forgotten the punchline of a joke.",
    "...sang a song out loud and messed the lyrics.",
    "...walked in on someone in the bathroom.",
    "...had someone walk in on me in the bathroom.",
    "...sent a text to the wrong person.",
    "...tried to pass a silent fart, but it came out loud instead.",
    "...tripped in public.",
    "...wet the bed after childhood.",
    "...accidentally pooped my pants.",
    "...attempted martial arts moves while by myself.",
    "...drove over a curb.",
    "...mistaken a man for a women or vice versa.",
    "...laughed so hard, I peed my pants.",
    "...picked a wedgie in public.",
    "...called the wrong person, but pretended I meant to call them.",
    "...gone into the wrong restroom.",
    "...been so freaked to be outside at night, that I ran back in.",
    "...lost my swimwear bottoms.",
    "...had diarrhea at a friend's house.",
    "...broken a piece of furniture by sitting on it.",
    "...arrived somewhere late and had everyone staring at me.",
    "...had food stuck in my teeth all day.",
    "...walked around with my zipper down.",
    "...bought a children's toy for myself, as an adult.",
    "...recorded video of myself singing or dancing.",
    "...been caught picking my nose.",
    "...gotten something stuck in my nose.",
    "...greeted someone I thought was someone else.",
    # Spicier additions, 27 September 2026
    "...had sex in a car.",
    "...used a safeword.",
    "...been tied up.",
    "...tied someone else up.",
    "...worn a collar.",
    "...been spanked hard enough to leave marks.",
    "...sent a nude.",
    "...hooked up with someone I met on Discord.",
    "...been walked in on during sex.",
    "...faked an orgasm.",
    "...been edged for over an hour.",
    "...had a threesome.",
    "...kissed someone of the same gender.",
    "...used a vibrator in public.",
    "...had sex in a public place.",
    "...joined the mile-high club.",
    "...watched porn with a partner.",
    "...roleplayed a boss and employee scene.",
    "...begged for it.",
    "...made someone beg.",
    "...called someone Daddy or Mommy in bed.",
    "...melted from being called a good girl, good boy or good pet.",
    "...had a sex dream about someone in this server.",
    "...bought lingerie just for one night.",
    "...been blindfolded during sex.",
    "...used ice or wax in the bedroom.",
    "...let a partner control my orgasms.",
    "...sexted at work.",
    "...recorded myself.",
    "...had sex more than five times in one day.",
    "...cried during or after a scene.",
    "...hit subspace.",
    "...been in a D/s relationship.",
    "...owned someone.",
    "...been owned.",
    "...shopped at a sex shop in person.",
    "...hidden a toy when someone came over.",
    "...been turned on by someone's voice alone.",
    "...hooked up with an ex.",
    "...been to a play party.",
    "...been to a strip club.",
    "...hooked up with someone whose name I didn't know.",
    "...used food in the bedroom.",
    "...worn a plug outside the house.",
    "...said the wrong name in bed.",
    "...kept going after getting caught.",
    "...worn a partner's clothes to feel close to them.",
    "...been teased in public until I couldn't think straight.",
]
